CREATE OR REPLACE TYPE "C##XCHEL_MEDICAL_RECORDS".DISEASE_BY_CLINICAL_HISTORY_TYPE AS OBJECT (
    UUID VARCHAR2(36),
    CHRONIC_DISEASE_ID NUMBER,
    ACTIVE CHAR(1)
);
/

CREATE OR REPLACE TYPE "C##XCHEL_MEDICAL_RECORDS".DISEASE_BY_CLINICAL_HISTORY_LIST AS TABLE OF C##XCHEL_MEDICAL_RECORDS.DISEASE_BY_CLINICAL_HISTORY_TYPE;
/

CREATE OR REPLACE PROCEDURE "C##XCHEL_MEDICAL_RECORDS".SP_ADD_MEDICAL_HISTORY(
    P_UUID IN VARCHAR2,
    P_ALLERGIES IN VARCHAR2,
    P_WEIGHT IN FLOAT,
    P_HEIGHT IN FLOAT,
    P_BLOOD_PRESSURE IN VARCHAR2,
    P_HEART_RATE_BPM IN NUMBER,
    P_LAST_MEDICAL_PRESCRIPTION_UUID IN VARCHAR2,
    P_PATIENT_UUID IN VARCHAR2,
    P_ACTIVE IN CHAR,
    P_CHRONIC_DISEASES IN DISEASE_BY_CLINICAL_HISTORY_LIST,
    P_RESULT_ID OUT NUMBER
)
AS
    V_MEDICAL_HISTORY_ID NUMBER;
BEGIN
    INSERT INTO "C##XCHEL_MEDICAL_RECORDS"."MEDICAL_RECORDS"
    (UUID, ALLERGIES, WEIGHT, HEIGHT, BLOOD_PRESSURE, HEART_RATE_BPM, 
     LAST_MEDICAL_PRESCRIPTION_UUID, PATIENT_UUID, ACTIVE)
    VALUES (P_UUID, P_ALLERGIES, P_WEIGHT, P_HEIGHT, P_BLOOD_PRESSURE, P_HEART_RATE_BPM,
            P_LAST_MEDICAL_PRESCRIPTION_UUID, P_PATIENT_UUID, P_ACTIVE)
    RETURNING ID INTO V_MEDICAL_HISTORY_ID;

    FOR i IN 1 .. P_CHRONIC_DISEASES.COUNT LOOP
        INSERT INTO "C##XCHEL_MEDICAL_RECORDS"."DISEASES_BY_CLINICAL_HISTORY"
        (UUID, CLINICAL_HISTORY_ID, CHRONIC_DISEASE_ID, ACTIVE)
        VALUES (P_CHRONIC_DISEASES(i).UUID, V_MEDICAL_HISTORY_ID, P_CHRONIC_DISEASES(i).CHRONIC_DISEASE_ID, P_CHRONIC_DISEASES(i).ACTIVE);
    END LOOP;

    P_RESULT_ID := V_MEDICAL_HISTORY_ID;
END;
/

CREATE OR REPLACE PROCEDURE "C##XCHEL_MEDICAL_RECORDS".SP_DELETE_MEDICAL_HISTORY(P_UUID VARCHAR2) AS
BEGIN
    UPDATE "C##XCHEL_MEDICAL_RECORDS"."MEDICAL_RECORDS" SET ACTIVE = 'N' WHERE UUID = P_UUID;
END;
/

CREATE OR REPLACE PROCEDURE "C##XCHEL_MEDICAL_RECORDS".SP_EDIT_MEDICAL_HISTORY(
    P_UUID IN VARCHAR2,
    P_ALLERGIES IN VARCHAR2,
    P_WEIGHT IN FLOAT,
    P_HEIGHT IN FLOAT,
    P_BLOOD_PRESSURE IN VARCHAR2,
    P_HEART_RATE_BPM IN NUMBER,
    P_LAST_MEDICAL_PRESCRIPTION_UUID IN VARCHAR2,
    P_PATIENT_UUID IN VARCHAR2,
    P_ACTIVE IN CHAR,
    P_CHRONIC_DISEASES IN DISEASE_BY_CLINICAL_HISTORY_LIST,
    P_RESULT_ID OUT NUMBER
) AS
BEGIN
    -- 1. Actualizar la tabla medical_records
    UPDATE "C##XCHEL_MEDICAL_RECORDS"."MEDICAL_RECORDS"
    SET ALLERGIES = P_ALLERGIES,
        WEIGHT = P_WEIGHT,
        HEIGHT = P_HEIGHT,
        BLOOD_PRESSURE = P_BLOOD_PRESSURE,
        HEART_RATE_BPM = P_HEART_RATE_BPM,
        LAST_MEDICAL_PRESCRIPTION_UUID = P_LAST_MEDICAL_PRESCRIPTION_UUID,
        PATIENT_UUID = P_PATIENT_UUID,
        ACTIVE = P_ACTIVE
    WHERE UUID = P_UUID;

    -- 2. Procesar las enfermedades crónicas (insertar o actualizar)
    FOR i IN 1..P_CHRONIC_DISEASES.COUNT LOOP
        DECLARE
            V_COUNT NUMBER;
        BEGIN
            -- Verificar si la enfermedad ya existe
            SELECT COUNT(*) INTO V_COUNT
            FROM "C##XCHEL_MEDICAL_RECORDS"."DISEASES_BY_CLINICAL_HISTORY"
            WHERE UUID = P_CHRONIC_DISEASES(i).UUID;
            
            IF V_COUNT = 0 THEN
                -- Si no existe, insertar la enfermedad crónica
                INSERT INTO "C##XCHEL_MEDICAL_RECORDS"."DISEASES_BY_CLINICAL_HISTORY"
                (UUID, CLINICAL_HISTORY_ID, CHRONIC_DISEASE_ID, ACTIVE)
                VALUES (
                    P_CHRONIC_DISEASES(i).UUID, 
                    (SELECT ID FROM "C##XCHEL_MEDICAL_RECORDS"."MEDICAL_RECORDS" WHERE UUID = P_UUID),
                    P_CHRONIC_DISEASES(i).CHRONIC_DISEASE_ID,
                    P_CHRONIC_DISEASES(i).ACTIVE
                );
            ELSE
                -- Si existe, actualizar el estado de la enfermedad crónica
                UPDATE "C##XCHEL_MEDICAL_RECORDS"."DISEASES_BY_CLINICAL_HISTORY"
                SET ACTIVE = 'Y'
                WHERE UUID = P_CHRONIC_DISEASES(i).UUID;
            END IF;
        END;
    END LOOP;

    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE "C##XCHEL_MEDICAL_RECORDS".SP_GET_ALL_MEDICAL_RECORDS(P_RESULT_CURSOR OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_RESULT_CURSOR FOR
        SELECT
            "MR".*,
            "DBCH"."UUID" AS "DBCH_UUID", "DBCH"."ACTIVE" AS "DBCH_ACTIVE",
            "CD"."UUID" AS "CD_UUID", "CD"."NAME" AS "CD_NAME", "CD"."ACTIVE" AS "CD_ACTIVE"
        FROM
            "C##XCHEL_MEDICAL_RECORDS"."MEDICAL_RECORDS" "MR"
        LEFT JOIN
            "C##XCHEL_MEDICAL_RECORDS"."DISEASES_BY_CLINICAL_HISTORY" "DBCH" ON "MR"."ID" = "DBCH"."CLINICAL_HISTORY_ID"
        LEFT JOIN
            "C##XCHEL_MEDICAL_RECORDS"."CHRONIC_DISEASES" "CD" ON "DBCH"."CHRONIC_DISEASE_ID" = "CD"."ID"
        WHERE
            "MR"."ACTIVE" = 'Y';
END;
/

CREATE OR REPLACE PROCEDURE "C##XCHEL_MEDICAL_RECORDS".SP_GET_MEDICAL_HISTORY_BY_UUID(P_UUID IN VARCHAR2, P_RESULT_CURSOR OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_RESULT_CURSOR FOR
        SELECT
            "MR".*,
            "DBCH"."UUID" AS "DBCH_UUID", "DBCH"."ACTIVE" AS "DBCH_ACTIVE",
            "CD"."UUID" AS "CD_UUID", "CD"."NAME" AS "CD_NAME", "CD"."ACTIVE" AS "CD_ACTIVE"
        FROM
            "C##XCHEL_MEDICAL_RECORDS"."MEDICAL_RECORDS" "MR"
        LEFT JOIN
            "C##XCHEL_MEDICAL_RECORDS"."DISEASES_BY_CLINICAL_HISTORY" "DBCH" ON "MR"."ID" = "DBCH"."CLINICAL_HISTORY_ID"
        LEFT JOIN
            "C##XCHEL_MEDICAL_RECORDS"."CHRONIC_DISEASES" "CD" ON "DBCH"."CHRONIC_DISEASE_ID" = "CD"."ID"
        WHERE
            "MR"."ACTIVE" = 'Y' AND
            "MR"."UUID" = P_UUID;
END;
/