services:
  xchel_medical_history_app:
    container_name: xchel_medical_history
    image: xchel_medical_history:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - ORACLE_DATABASE_HOST=oracle_db_xchel_medical_history
      - ORACLE_DATABASE_PORT=1521
      - ORACLE_DATABASE_SERVICE_NAME=FREE
      - ORACLE_DATABASE_USERNAME=C##XCHEL_MEDICAL_RECORDS
      - ORACLE_DATABASE_PASSWORD=LKPW3XVj8crFUB-6CY_f
      - ORACLE_DATABASE_DEFAULT_SCHEMA=C##XCHEL_MEDICAL_RECORDS
      - REDIS_HOST=redis_xchel_medical_history
      - REDIS_PORT=6379
    depends_on:
      - oracle_db_xchel_medical_history
      - redis_xchel_medical_history
  oracle_db_xchel_medical_history:
    container_name: oracle_db_xchel_medical_history
    image: container-registry.oracle.com/database/free:23.7.0.0-amd64
    ports:
      - 1521:1521
    environment:
      - ORACLE_PWD=LKPW3XVj8crFUB-6CY_f
    volumes:
      - ./src/main/resources/db/scripts_setup:/opt/oracle/scripts/startup
  redis_xchel_medical_history:
    container_name: redis_xchel_medical_history
    image: redis:7.4.2
    ports:
      - 6379:6379
