CREATE USER C##XCHEL_MEDICAL_RECORDS IDENTIFIED BY "LKPW3XVj8crFUB-6CY_f";
GRANT CONNECT, RESOURCE TO C##XCHEL_MEDICAL_RECORDS;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO C##XCHEL_MEDICAL_RECORDS;
ALTER USER C##XCHEL_MEDICAL_RECORDS QUOTA UNLIMITED ON USERS;
