spring:
  application:
    name: medical-history
  datasource:
    url: jdbc:postgresql://localhost:5432/xchel_medical_records
    username: postgres
    password: SoloPostgres1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect